global.fetch = require('node-fetch');

import { getCurriculum } from '../background/getCurriculum';

it.concurrent("should fetch and parse ITC11's curriculum", async () => {
  const careerCode = 'ITC11';
  const curriculum = await getCurriculum(careerCode);
  expect(curriculum).toStrictEqual(ITC11Curriculum);
});

const ITC11Curriculum = {
  spanishClassNames: {
    'F-1001': 'Introducción a la física',
    'H-1001': 'Inglés remedial I',
    'H-1002': 'Inglés remedial II',
    'H-1003': 'Inglés remedial III',
    'H-1004': 'Inglés remedial IV',
    'H-1005': 'Inglés remedial V',
    'H-1015': 'Fundamentos de la escritura',
    'MA-1001': 'Introducción a las matemáticas',
    'TC-1001': 'Introducción a la computación',
    'DS-1003': 'Ciencias naturales y desarrollo sustentable',
    'F-1002': 'Física I',
    'H-1016': 'Lengua extranjera',
    'MA-1015': 'Matemáticas I',
    'TC-1003': 'Matemáticas discretas',
    'TC-1014': 'Fundamentos de programación',
    'TC-1022': 'Introducción a la ingeniería en tecnologías computacionales',
    'AD-1005': 'Administración e innovación en modelos de negocios',
    'H-1040': 'Análisis y expresión verbal',
    'MA-1017': 'Matemáticas II',
    'TC-1015': 'Fundamentos de diseño interactivo',
    'TC-1016': 'Organización computacional',
    'TC-2016': 'Programación orientada a objetos',
    'F-1005': 'Electricidad y magnetismo',
    'H-1018': 'Ética, persona y sociedad',
    'MA-1006': 'Probabilidad y estadística',
    'MA-2009': 'Matemáticas III',
    'TC-1018': 'Estructura de datos',
    'TC-1019': 'Fundamentos de ingeniería de software',
    'H-2001': 'Expresión verbal en el ámbito profesional',
    'TC-1020': 'Bases de datos',
    'TC-1021': 'Proyecto de desarrollo de videojuegos',
    'TC-2017': 'Análisis y diseño de algoritmos',
    'TC-2018': 'Fundamentos de redes',
    'TC-2019': 'Métodos numéricos en ingeniería',
    'HS-2000': 'Humanidades y bellas artes',
    'MA-1019': 'Álgebra lineal',
    'TC-2004': 'Análisis y modelación de sistemas de software',
    'TC-2008': 'Sistemas operativos',
    'TC-2020': 'Matemáticas computacionales',
    'TC-2022': 'Interconexión de redes',
    'EM-1005': 'Emprendimiento',
    'TC-2024': 'Proyectos de desarrollo para dispositivos móviles',
    'TC-2025': 'Programación avanzada',
    'TC-3041': 'Bases de datos avanzadas',
    'TC-3045': 'Calidad y pruebas de software',
    'TI-2011': 'Evaluación y administración de proyectos',
    'HS-2005': 'Ciudadanía',
    'TC-2006': 'Lenguajes de programación',
    'TC-2026': 'Desarrollo de aplicaciones web',
    'TC-2027': 'Seguridad informática',
    'TC-3002': 'Administración de proyectos de ingeniería de software',
    'VA-2010': 'Tópicos I',
    'TC-2007': 'Métodos cuantitativos y simulación',
    'TC-3022': 'Gráficas computacionales',
    'TC-3048': 'Diseño de compiladores',
    'TC-3049': 'Diseño y arquitectura de software',
    'TC-3052': 'Laboratorio de desarrollo de aplicaciones Web',
    'VA-2011': 'Tópicos II',
    'VA-2012': 'Tópicos III',
    'HS-2006': 'Ética aplicada',
    'TC-2011': 'Sistemas inteligentes',
    'TC-3054':
      'Proyecto integrador para el desarrollo de soluciones empresariales',
    'TI-3035': 'Introducción a la vida profesional',
    'VA-2013': 'Tópicos IV',
    'VA-2014': 'Tópicos V',
    'VA-2015': 'Tópicos VI',
  },
  englishClassNames: {
    'F-1001': 'Introduction to Physics',
    'H-1001': 'Remedial English I',
    'H-1002': 'Remedial English II',
    'H-1003': 'Remedial English III',
    'H-1004': 'Remedial English IV',
    'H-1005': 'Remedial English V',
    'H-1015': 'Spanish Composition',
    'MA-1001': 'Introduction to Mathematics',
    'TC-1001': 'Introduction to Computer Science',
    'DS-1003': 'Natural Sciences and Sustainable Development',
    'F-1002': 'Physics I',
    'H-1016': 'Foreign Language',
    'MA-1015': 'Mathematics I',
    'TC-1003': 'Discrete Mathematics',
    'TC-1014': 'Programming Fundamentals',
    'TC-1022': 'Introduction to Computer Science and Technology',
    'AD-1005': 'Management and Business Model Innovation',
    'H-1040': 'Verbal Expression and Analysis',
    'MA-1017': 'Mathematics II',
    'TC-1015': 'Introduction to Interactive Design',
    'TC-1016': 'Computer Organization',
    'TC-2016': 'Object-Oriented Programming',
    'F-1005': 'Electricity and Magnetism',
    'H-1018': 'Ethics, Self and Society',
    'MA-1006': 'Probability and Statistics',
    'MA-2009': 'Mathematics III',
    'TC-1018': 'Data Structures',
    'TC-1019': 'Introduction to Software Engineering',
    'H-2001': 'Verbal Expression in the Workplace',
    'TC-1020': 'Databases',
    'TC-1021': 'Videogame Development Project',
    'TC-2017': 'Analysis and Design of Algorithms',
    'TC-2018': 'Introduction to Networks',
    'TC-2019': 'Numerical Methods in Engineering',
    'HS-2000': 'Humanities and Fine Arts',
    'MA-1019': 'Linear Algebra',
    'TC-2004': 'Analysis and Modeling of Software Systems',
    'TC-2008': 'Operating Systems',
    'TC-2020': 'Computational Mathematics',
    'TC-2022': 'Network Interconnection',
    'EM-1005': 'Entrepreneurship',
    'TC-2024': 'Mobile Application Development Projects',
    'TC-2025': 'Advanced Programming',
    'TC-3041': 'Advanced Database Systems',
    'TC-3045': 'Software Quality and Testing',
    'TI-2011': 'Project Evaluation and Management',
    'HS-2005': 'Citizenship',
    'TC-2006': 'Programming Languages',
    'TC-2026': 'Web Applications Development',
    'TC-2027': 'Computer and Information Security',
    'TC-3002': 'Management of Software Engineering Projects',
    'VA-2010': 'Topics I',
    'TC-2007': 'Quantitative Methods and Simulation',
    'TC-3022': 'Computer Graphics',
    'TC-3048': 'Compiler Design',
    'TC-3049': 'Software Design and Architecture',
    'TC-3052': 'Web Application Development Laboratory',
    'VA-2011': 'Topics II',
    'VA-2012': 'Topics III',
    'HS-2006': 'Applied Ethics',
    'TC-2011': 'Intelligent Systems',
    'TC-3054': 'Business Solution Development Capstone Project',
    'TI-3035': 'Introduction to Professional Development',
    'VA-2013': 'Topics IV',
    'VA-2014': 'Topics V',
    'VA-2015': 'Topics VI',
  },
  semesterNames: [
    ['Semestre Remedial', 'Remedial Semester'],
    ['Primer Semestre', 'First Semester'],
    ['Segundo Semestre', 'Second Semester'],
    ['Tercer Semestre', 'Third Semester'],
    ['Cuarto Semestre', 'Fourth Semester'],
    ['Quinto Semestre', 'Fifth Semester'],
    ['Sexto Semestre', 'Sixth Semester'],
    ['Séptimo Semestre', 'Seventh Semester'],
    ['Octavo Semestre', 'Eighth Semester'],
    ['Noveno Semestre', 'Ninth Semester'],
  ],
};
