name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-extension:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build extension
        run: yarn build

      - name: Create zip from build folder
        run: |
          mv build tec-transcript-translater
          zip -r tec-transcript-translater.zip tec-transcript-translater/*

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: tec-transcript-translater.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
